from fastapi import status

# 成功响应
HTTP_OK = status.HTTP_200_OK
HTTP_CREATED = status.HTTP_201_CREATED
HTTP_ACCEPTED = status.HTTP_202_ACCEPTED
HTTP_NO_CONTENT = status.HTTP_204_NO_CONTENT

# 客户端错误
HTTP_BAD_REQUEST = status.HTTP_400_BAD_REQUEST
HTTP_UNAUTHORIZED = status.HTTP_401_UNAUTHORIZED
HTTP_FORBIDDEN = status.HTTP_403_FORBIDDEN
HTTP_NOT_FOUND = status.HTTP_404_NOT_FOUND
HTTP_CONFLICT = status.HTTP_409_CONFLICT
HTTP_UNPROCESSABLE_ENTITY = status.HTTP_422_UNPROCESSABLE_ENTITY

# 服务器错误
HTTP_INTERNAL_SERVER_ERROR = status.HTTP_500_INTERNAL_SERVER_ERROR
